/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "UART_1.h"
#include "SDA_1_aliases.h"
#include "SDA_1.h"
#include "SCL_1_aliases.h"
#include "SCL_1.h"
#include "I2C_1.h"
#include "I2C_1_PVT.h"
#include "Clock_1.h"
#include "Heater_ENA_aliases.h"
#include "Heater_ENA.h"
#include "PWM_1.h"
#include "Counter_1.h"
#include "TimerOutput_aliases.h"
#include "TimerOutput.h"
#include "Clock_2.h"
#include "ADC_SAR_1.h"
#include "Temperature_aliases.h"
#include "Temperature.h"
#include "Heater_IN1_aliases.h"
#include "Heater_IN1.h"
#include "Heater_IN2_aliases.h"
#include "Heater_IN2.h"
#include "UART_1_IntClock.h"
#include "ADC_SAR_1_IRQ.h"
#include "ADC_SAR_1_theACLK.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

